Update setup.mdx
widgetbook/widgetbook pull request #1127
Opened 2024-01-09 13:30 UTC by LucasJosefiak

2024-01-09 16:20 UTC, jenshor requested changes

2024-01-09 16:20 UTC, jenshor commented on docs/assets/integrating-github/4_new.png
This file should be renamed

2024-01-09 16:20 UTC, jenshor commented on docs/assets/screenshots/github_app_installation.png
This file needs to removed from the PR

2024-01-09 16:20 UTC, jenshor commented on docs/widgetbook-cloud/projects.mdx
This page has to be removed. Might also need to be removed from the docs.json file

2024-01-09 16:20 UTC, jenshor commented on docs/widgetbook-cloud/reviews.mdx
> +1. Make sure to incorporate the [widgetbook_generator package](https://pub.dev/packages/widgetbook_generator) version `{{ versions.generator }}`. No additional configuration needed.
Let's remove `No additional configuration needed.`

2024-01-09 16:20 UTC, jenshor commented on docs/widgetbook-cloud/reviews.mdx
> +2. Integrate the [widgetbook package](https://pub.dev/packages/widgetbook) version `{{ versions.widgetbook }}`. No extra setup required.
Let's remove `No extra setup required.`

2024-01-09 16:20 UTC, jenshor commented on docs/widgetbook-cloud/reviews.mdx
> +4. Set up our GitHub app.
Let's put a link to the page here

2024-01-09 16:20 UTC, jenshor commented on docs/widgetbook-cloud/reviews.mdx
> +5. Upload a build of your base branch, e.g. main. See [how to upload a build](https://docs.widgetbook.io/widgetbook-cloud/hosting).
main should be formatted as `main`. 

The link must be relative and must not contain `https:`

2024-01-09 16:20 UTC, jenshor commented on docs/widgetbook-cloud/reviews.mdx
> +6. Add new or change existing Widgetbook use cases in your feature branch. Note: Without changed use cases, the review feature won't work, as there would be nothing to review.
Let's add another point here saying create a branch. 
Then we have what is currently 6 that says: Make a change, add a use case etc.

2024-01-09 16:20 UTC, jenshor commented on docs/widgetbook-cloud/reviews.mdx
> +8. Upload a build for the feature branch with changed Widgetbook use cases.
Here the command is `widgetbook publish --api-key <API> --base-branch main`

2024-01-09 16:20 UTC, jenshor commented on docs/widgetbook-cloud/reviews.mdx
> +9. Publish a review using this command: `widgetbook publish --api-key KEY --base-branch BASE-BRANCH`.
This should be part of what is currently 8.

2024-01-25 11:34 UTC, jenshor approved these changes

2024-01-25 11:34 UTC, merged

2024-05-03 12:04 UTC, benitagrace commented on docs/assets/integrating-github/4.png
test

2024-05-03 14:17 UTC, benitagrace commented on docs/assets/integrating-github/4.png
khkhkh