feat: improve duration knob
widgetbook/widgetbook pull request #1226
Opened 2024-08-10 17:02 UTC by Mastersam07

The DurationKnob today is s textfield that takes in millisecond input. It could be tricky while working with durations in hours, or days.

This PR changes the DurationField to show days, hours, minutes, seconds, allowing them to easily be selected and updated.

### List of issues which are fixed by the PR
Closes #1148 

### Screenshots
![Screenshot 2024-08-10 at 17 44 54](https://github.com/user-attachments/assets/3ba36490-aaad-4ed1-9343-3b85e10bd086)

https://github.com/user-attachments/assets/03770d2a-070a-4f99-b909-c15827bf1834

### Checklist

- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on [Discord].

[CLA]: https://docs.google.com/forms/d/e/1FAIpQLScuRfjUzENsLsmQgqZlGLxMKbFi7zuXoPARyXytoyQrq7ntUw/viewform
[Discord]: https://discord.com/invite/zT4AMStAJA

2024-08-14 13:20 UTC, YoussefRaafatNasry requested changes
Intersting change! 

The UX of changing the minutes, or hours to two-digit value, was really hard to use, we should think of ways to improve it. Maybe it makes sense to split the values in multiple `TextFields` to allow for better UX.

2024-08-18 13:10 UTC, Mastersam07 commented
> Intersting change!
> 
> The UX of changing the minutes, or hours to two-digit value, was really hard to use, we should think of ways to improve it. Maybe it makes sense to split the values in multiple `TextFields` to allow for better UX.

Made the changes.

2024-09-08 14:02 UTC, Mastersam07 commented
@yousinix

2024-09-09 11:36 UTC, yousinix commented
Hey, @Mastersam07!
Sorry I've completely missed to submit a review for this PR.
I will submit it now.

2024-09-09 12:07 UTC, yousinix requested changes

2025-05-26 06:37 UTC, yousinix commented
This PR is closed for being stale for long time.
Feel free to request re-open if any updates are introduced.

2025-05-26 06:37 UTC, closed without merging