fix: Nullable Double Slider Knob's initialValue Cannot be null issue#901
widgetbook/widgetbook pull request #933
Opened 2023-10-04 19:18 UTC by Utkarsh4517

*Added an explicit check if  the initialValue is null before applying the default value. If it's null, the provided null value will be respected; otherwise, the default logic will be applied.*

### List of issues which are fixed by the PR
*When using context.knobs.doubleOrNull.slider() with an initialValue: null, the initial value is set to a non-null value.*

### Checklist

- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on [Discord].

[CLA]: https://docs.google.com/forms/d/e/1FAIpQLScuRfjUzENsLsmQgqZlGLxMKbFi7zuXoPARyXytoyQrq7ntUw/viewform
[Discord]: https://discord.com/invite/zT4AMStAJA

2023-10-05 09:54 UTC, Utkarsh4517 commented
@YoussefRaafatNasry Can you please give a review to this.

2023-10-05 11:19 UTC, YoussefRaafatNasry requested changes
Please consider the following along with the proposed change:

1. Adding more tests to validate the new logic.
2. Changing `knobs.double.slider`'s `initialValue` as well to be a non-null by default.
3. Adding [`CHANGELOG.md`](https://github.com/widgetbook/widgetbook/blob/main/packages/widgetbook/CHANGELOG.md) entries to let other people know what we have fixed in the upcoming release.

2023-10-05 11:19 UTC, YoussefRaafatNasry commented on packages/widgetbook/lib/src/knobs/builders/double_knobs_builder.dart
> +    }
This change will be **breaking** for all users who have an `initialValue` of null without `min` and `max` values set, due to the null assertion on `min!` and `max!`

Consider the following change instead:
```suggestion
    return onKnobAdded(
      DoubleSliderKnob.nullable(
        label: label,
        value: initialValue,
        description: description,
        min: min ?? (initialValue == null ? 0 : initialValue - 10),
        max: max ?? (initialValue == null ? 10 : initialValue + 10),
        divisions: divisions,
      ),
    );
```

2023-10-06 15:23 UTC, Utkarsh4517 commented
Hey @YoussefRaafatNasry  I have made the necessary changes can You please take a look :)

2023-10-08 10:22 UTC, YoussefRaafatNasry commented
@Utkarsh4517 Please consider the other points mentioned in [the review comment](https://github.com/widgetbook/widgetbook/pull/933#pullrequestreview-1659580796) before I review this again.

2023-10-17 12:51 UTC, closed without merging

2023-10-17 12:51 UTC, YoussefRaafatNasry commented
This PR has been closed for being stale for so long.